### PR TITLE
Fix thumbs, tags and FB Alpha to FBNeo

### PR DESCRIPTION
**Pull request by predr**
Hello... This fixes 3 issues with images in playlists I found trying out ludo.

1. Unable to find thumbs with special characters in ./ludo/thumbnails/ directory

2. Unable to download Arcade thumbs because server returns 404 on 'FB Alpha' urls.

3. Showing black image for unknown game tags.

Note: Requires updates to database and assets repos changing names from 'FB Alpha' to 'FBNeo' ~~and will break user playlist (must rename existing 'FB Alpha' playlist)~~.

### CODE REVIEW

**Comment by kivutar** [comment]
Hi, thanks, can you explain the change with `getPaths` please?

**Comment by predr** [comment]
Sure, moved code that was in Load() to separate function so it can be reused by Update() function. Returns the list of full/absolute paths to playlists.

**Comment by kivutar** [comment]
OK to merge this, but I have to find a FBNeo set. My current FBA set doesn't scan with this new RDB.

**Comment by predr** [comment]
Just to clarify here: `FB Alpha - Arcade Games.rdb` [is using](https://github.com/libretro/ludo/pull/303/commits/4774927b07c39b90ef38856b3d47a2aca0f34691#diff-8882cd6cb02b54b11db3a130486c0861L34) `fbneo_libretro` core. So just renaming [FB Alpha - Arcade Games.rdb](https://github.com/kivutar/ludo-database/blob/master/FB%20Alpha%20-%20Arcade%20Games.rdb) to `FBNeo - Arcade Games.rdb` should produce same scan results.

**Pull request merged**
