### PR TITLE
Hexagon UI

### PR DESCRIPTION
**Pull request by kivutar**
screen shot 2018-10-26 at 9 11 07 pm

### CODE REVIEW

**Comment by RobLoach** [comment]
Looking pretty nice... Kind of enjoy this one more.

**Comment by RobLoach** [comment]
Unsure why I get this.....

screenshot at 2018-10-25 10-12-19

**Comment by RobLoach** [comment]
Worked with circles...

screenshot at 2018-10-25 10-14-09

**Comment by kivutar** [comment]
@RobLoach It was a missing image in the assets

**Pull request merged**
