### PR TITLE
Add Wireless Xbox Controller

### PR DESCRIPTION
**Pull request by grinsted**
My SN30 says it is a "Wireless Xbox Controller".

### CODE REVIEW

**Comment by kivutar** [comment]
SN30 are not supposed to use this name. Is your firmware up to date?

**Comment by johnnyq** [comment]
I just found this out about 2 monthes ago, but the 8bit do controller can be set to emulate an xbox controller if you press start and x when off. It will set the controller to xbox mode. The next time you turn it off then on it will stay in xbox mode. to switch it back I think its start + B when off.

**Comment by johnnyq** [comment]
This would be a nice merge, as all 8bitdo controllers can mimic Xbox Controller

**Comment by jstine35** [comment]
Same, 👍 for merging.

**Review by kivutar — APPROVED** [review]

**Comment by kivutar** [comment]
Can we have the same thing for Linux and OSX?

**Pull request merged**
