### PR TITLE
Add SHA256 Checksum generation for binaries

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**

### CODE REVIEW

**Comment by kivutar** [comment]
This won't work because you're adding the checksum generation as a separate branch in the travis matrix.
You need to use another travis callback that executes after script, and before release.
Also, if checksum.txt contains multiple checksums, can you please make it plural?

**Comment by julianxhokaxhiu** [comment]
@kivutar I'll look into it. Related to make it plural I agree with you.

Finally CRC check is included, although sha256 checksum is to guarantee you're downloading and expecting something that matches what you as an author release ( https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_hijacking ). Every Linux does that, and it would benefit also me as an author for eg. to package and bump the ludo package on AUR ( https://aur.archlinux.org/packages/ludo/ ), which otherwise I would have to download and run the checksum command myself.

**Comment by julianxhokaxhiu** [comment]
Updated to use the hook `before_deploy`, it should do the job. Feel feee to review. Thanks :)

**Comment by kivutar** [comment]
Oh I see, for packaging, got it.

**Comment by julianxhokaxhiu** [comment]
Thank you for merging :)

**Comment by kivutar** [comment]
I had to revert, as the builds are running per OS, the command to generate the checksum on RPi was failing when building for PC.
Can you come with another way of generating the checksum? Maybe one file per archive?

**Comment by julianxhokaxhiu** [comment]
Let me try something out.

**Comment by julianxhokaxhiu** [comment]
Let's continue on #189

**Pull request merged**
