### PR TITLE
Add support for iBuffalo classic controller and 8Bitdo SF30/SN30

### PR DESCRIPTION
**Pull request by beshrkayali**
Hey,

This adds config for a couple of snes controllers I have.

The iBuffalo classic controller comes up under the name "USB,2-axis 8-button gamepad  " with some extra spaces at the end, which is why I thought it might be a good idea to trim white space from `glfw.Joystick.GetName(joy)`, not sure if this could have unintended side effects on other controllers, but I don't think it should.

Also fixes what I suppose is a typo in `input/binds_linux.go` (fox -> for) :)

### CODE REVIEW

**Comment by kivutar** [comment]
Hi and thanks for the PR.

The policy about joypad is that I usually only accept PRs for pads I own, since I'm the only active maintainer. I can only regression test the pads I have access to.

We can merge this if you are OK to spend time:

  * checking that the support for this pad doesn't break
  * checking that this pad doesn't break other pads.

It would also need to have binding for OSX and Windows, as we try to avoid having stuff that work on one system and not on another.

Also, I plan to ask contributors to sign a CLA allowing me to dual license Ludo. Please tell me if you're OK with this idea.

**Comment by beshrkayali** [comment]
Hi, thanks for the reply. I think this policy makes sense!

Unfortunately I only have access to a PS4 controller, which I did test and it works ok. I'm ok with continuing to support these two pads as well, but I understand that this could potentially slow down dev work as you won't be able to test everything yourself. 

I will add the appropriate config for them for Windows later today anyway, not sure if I'll be able to do that for OSX as I don't own a Mac to test on, but I might be able to borrow one later this week.

Regarding CLA signing, I personally don't have an issue with it for this PR.

**Comment by kivutar** [comment]
Thanks, I'll merge this as soon as we have the configurations for the 3 OS!

**Comment by kivutar** [comment]
Hi, now that we switched to GLFW internal gamepad database, it's better to add new mappings upstream,

Here https://github.com/glfw/glfw/blob/33cd8b865d9289cfbcf3d95e6e68e4050b94fcd3/src/mappings.h
Here https://github.com/go-gl/glfw/blob/62640a716d485dcbf341a7c187227a4a99fb1eba/v3.3/glfw/glfw/src/mappings.h

Sorry for closing this. But I think it's a better long term solution.

**Pull request closed without merging**
